"use client";

import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import type { Message } from "@prisma/client"; // generated by Prisma

export function useMessages() {
  return useQuery<Message[]>({
    queryKey: ["messages"],
    queryFn: async () => {
      const res = await fetch("/api/messages");
      if (!res.ok) {
        throw new Error("Failed to fetch messages");
      }
      return res.json();
    },
  });
}

export function useCreateMessage(socket: any) {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: { content: string; author: string }) => {
      const res = await fetch("/api/messages", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(data),
      });

      if (!res.ok) {
        throw new Error("Failed to create message");
      }

      return res.json();
    },
    onSuccess: (createdMessage) => {
      // Update our own cache
      queryClient.invalidateQueries({ queryKey: ["messages"] });

      // Notify other clients via WebSocket
      if (socket) {
        socket.emit("message:created", {
          id: createdMessage.id,
        });
      }
    },
  });
}
